<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Radio */ ?>
<?php $_option = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_count = count($_selections); ?>
<?php $_default = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php foreach ($_selections as $_selection):
    if ($block->isSelected($_selection)):
        $description = $block->getDescription($_selection);
        $url = $_selection->getProductUrl();
        ?>
        <script type="text/x-magento-init">
            {
                "[data-gallery-role=choice-gallery-placeholder-<?php /* @escapeNotVerified */ echo $_option->getId() ?>]": {
                    "mage/gallery/gallery": {
                        "mixins":["magnifier/magnify"],
                        "magnifierOpts": {
                            "fullscreenzoom":"5",
                            "top":"0",
                            "left":"0",
                            "width":"100",
                            "height":"100",
                            "eventType":"hover",
                            "enabled":"true"
                        },
                        "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson($_selection); ?>,
                        "options": {
                            "nav": "dots",
                            "loop": true,
                            "keyboard": true,
                            "arrows": true,
                            "allowfullscreen": true,
                            "showCaption": false,
                            "width": 200,
                            "thumbwidth": 10,
                            "thumbheight": 10,
                            "height": 200,
                            "transitionduration": 300,
                            "transition": "slide",
                            "navarrows": true,
                            "navtype": "thumbs",
                            "navdir": "horizontal"
                        },
                        "fullscreen": {
                            "nav": "thumbs",
                            "loop": true,
                            "navdir": "horizontal",
                            "arrows": true,
                            "showCaption": false,
                            "transitionduration": 300,
                            "transition": "slide"
                        }
                    }
                }
            }
        </script>
    <?php break; endif;?>
<?php endforeach;?>

<div class="field option<?php echo ($_count>1) ? '':' no-option'; ?><?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <label class="label">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selections[0]) ?>
                <input type="hidden"
                    class="bundle-option-<?php echo (int)$_option->getId() ?>  product bundle option"
                    name="bundle_option[<?php echo (int)$_option->getId() ?>]"
                    value="<?php echo (int)$_selections[0]->getSelectionId() ?>"
                    id="bundle-option-<?php echo (int)$_option->getId() ?>-<?php echo (int)$_selections[0]->getSelectionId() ?>"
                    checked="checked"
                />
            <?php else:?>
                <?php if (!$_option->getRequired()): ?>
                    <div class="field choice">
                        <input type="radio"
                               class="radio product bundle option"
                               id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                               name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                               data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                               <?php echo ($_default && $_default->isSalable())?'':' checked="checked" ' ?>
                               value=""/>
                        <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
                            <span><?php /* @escapeNotVerified */ echo __('None') ?></span>
                        </label>
                    </div>
                <?php endif; ?>
                <?php foreach ($_selections as $_selection): ?>
                    <div class="field choice">
                        <input type="radio"
                               class="radio product bundle option change-container-classname"
                               id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                               <?php if ($_option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':true}"'?>
                               name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                               data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                               <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                               <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                               value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"/>
                        <label class="label"
                               for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>">
                            <span class="tip_<?php $_selection->getSelectionId()?>"><?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection) ?></span>
                            <span class="tip_<?php $_selection->getSelectionId()?>" style="display: none;"><?php /* @escapeNotVerified */ echo $block->getTooltip($_selection) ?></span>
                        </label>
                    </div>
                <?php endforeach; ?>
                <div id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></div>
                <div class="row">
                    <div data-gallery-role="choice-gallery-placeholder-<?php /* @escapeNotVerified */ echo $_option->getId() ?>" class="col-xs-6"></div>
                    <div class="col-xs-6">
                        <div id="choice-description-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"><?php echo $description ?></div>
                        <div><a id="choice-info-link-<?php /* @escapeNotVerified */ echo $_option->getId() ?>" target="_blank" href="<?php echo $url ?>"><?php echo _('more information') ?></a></div>
                    </div>
                </div>
            <?php endif; ?>
            <div class="field qty qty-holder<?php if (!$_canChangeQty) echo ' qty-disabled' ?>">
                <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input">
                    <span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                           id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                           class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                           type="number"
                           name="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           data-selector="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>