<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Select */ ?>
<?php $_option      = $block->getOption(); ?>
<?php $_selections  = $_option->getSelections(); ?>
<?php $_default     = $_option->getDefaultSelection(); ?>
<?php list($_defaultQty, $_canChangeQty) = $block->getDefaultValues(); ?>
<?php foreach ($_selections as $_selection):
    if ($block->isSelected($_selection)):
        $description = $block->getDescription($_selection);
        $url = $_selection->getProductUrl();
        ?>
        <script type="text/x-magento-init">
            {
                "[data-gallery-role=choice-gallery-placeholder-<?php /* @escapeNotVerified */ echo $_option->getId() ?>]": {
                    "mage/gallery/gallery": {
                        "mixins":["magnifier/magnify"],
                        "magnifierOpts": {
                            "fullscreenzoom":"5",
                            "top":"0",
                            "left":"0",
                            "width":"100",
                            "height":"100",
                            "eventType":"hover",
                            "enabled":"true"
                        },
                        "data": <?php /* @escapeNotVerified */ echo $block->getGalleryImagesJson($_selection); ?>,
                        "options": {
                            "nav": "dots",
                            "loop": true,
                            "keyboard": true,
                            "arrows": true,
                            "allowfullscreen": true,
                            "showCaption": false,
                            "width": 200,
                            "thumbwidth": 10,
                            "thumbheight": 10,
                            "height": 200,
                            "transitionduration": 300,
                            "transition": "slide",
                            "navarrows": true,
                            "navtype": "thumbs",
                            "navdir": "horizontal"
                        },
                        "fullscreen": {
                            "nav": "thumbs",
                            "loop": true,
                            "navdir": "horizontal",
                            "arrows": true,
                            "showCaption": false,
                            "transitionduration": 300,
                            "transition": "slide"
                        }
                    }
                }
            }
        </script>
    <?php break; endif;?>
<?php endforeach;?>

<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <?php if ($block->showSingle()): ?>
            <?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selections[0]) ?>
            <input type="hidden"
                   class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                   name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                   value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
        <?php else:?>
            <select id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"
                    name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                    data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                    class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> product bundle option bundle-option-select change-container-classname"
                <?php if ($_option->getRequired()) echo 'data-validate = {required:true}' ?>>
                <option value=""><?php /* @escapeNotVerified */ echo __('Choose a selection...') ?></option>
                <?php foreach ($_selections as $_selection): ?>
                    <option value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                        <?php if ($block->isSelected($_selection)) echo ' selected="selected"' ?>
                        <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>>
                        <?php /* @escapeNotVerified */ echo $_selection->getName() ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php endif; ?>
        <div class="row">
            <div data-gallery-role="choice-gallery-placeholder-<?php /* @escapeNotVerified */ echo $_option->getId() ?>" class="col-xs-6"></div>
            <div class="col-xs-6">
                <div id="choice-description-<?php /* @escapeNotVerified */ echo $_option->getId() ?>"><?php echo $description ?></div>
                <div><a id="choice-info-link-<?php /* @escapeNotVerified */ echo $_option->getId() ?>" target="_blank" href="<?php echo $url ?>"><?php echo __('more information') ?></a></div>
            </div>
        </div>
        <div class="nested">
            <div class="field qty qty-holder<?php if (!$_canChangeQty) echo ' qty-disabled' ?>">
                <label class="label" for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input">
                    <span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span>
                </label>
                <div class="control">
                    <input <?php if (!$_canChangeQty) echo ' disabled="disabled"' ?>
                           id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-qty-input"
                           class="input-text qty<?php if (!$_canChangeQty) echo ' qty-disabled' ?>"
                           type="number"
                           name="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           data-selector="bundle_option_qty[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                           value="<?php /* @escapeNotVerified */ echo $_defaultQty ?>"/>
                </div>
            </div>
        </div>
    </div>
</div>
